### ISSUE TITLE
Dealing with duplicity cache lock (.lock file)

### ISSUE THREAD

**Issue by darron1217** [blacklabelops/volumerize#8]
@blacklabelops 
While I was testing volumerize in a small sized storage, duplicity backup process was interrupt because of storage limitation.

This left .lock file at `/volumerize-cache` directory, which causes the error below
```
Another instance is already running with this archive directory
If you are sure that this is the  only instance running you may delete
the following lockfile and run the command again :
/volumerize-cache/3fe07cc0f71075f95f411fb55ec60120/lockfile.lock
```

How about adding a cache-removing script before start backing up?

**Comment by blacklabelops** [comment]
I am not really sure how to solve this.

The cache is really important for me. I am using backblaze backend backups. This means if i delete the cache then each time i backup i need to build up another cache.

This mean additional costs for backups because data is transferred from and to my cloud storage.

Maybe we need to make this configurable?

**Comment by darron1217** [comment]
@blacklabelops 
I mean removing `lockfile.lock` instead of removing whole cache

I actually didn't know the functionality of cache folder...
Yep, cache is important but (I guess) lockfile (which is orphaned) is not needed on next backup :)

**Comment by blacklabelops** [comment]
Im still trying to figure out, how to decide, if a lockfile is really orphaned.

**Comment by blacklabelops** [comment]
Added new cleanup script `cleanCacheLocks`.
